version: '3'
services:
  postgres:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=training
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data
    command: ["postgres", "-c", "log_statement=all"]
    #volumes:
    #  - ./data:/data
  pgadmin:
    image: dpage/pgadmin4:6.7
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@training.pl
      - PGADMIN_DEFAULT_PASSWORD=admin
